<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <PluginSystemName>DevOps.Dokku</PluginSystemName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ServerManager.Infrastructure\ServerManager.Infrastructure.csproj" Private="false" />
    <ProjectReference Include="..\..\ServerManager.Web.Framework\ServerManager.Web.Framework.csproj" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ServerManager.Plugin.DevOps.Dokku.Tests" />
  </ItemGroup>

</Project>
